// Code generated by "stringer -type=Format"; DO NOT EDIT.

package msg

import "strconv"

const _Format_name = "FormatMetricDataV1ArrayJsonFormatMetricDataV1ArrayMsgpFormatMetricDataArrayJsonFormatMetricDataArrayMsgp"

var _Format_index = [...]uint8{0, 27, 54, 79, 104}

func (i Format) String() string {
	if i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
